### ISSUE TITLE
how to host the build files

### ISSUE THREAD

**Issue by infacq** [juliancwirko/react-boilerplate#10]
now I can run `server.js` without any problem. How do I get run the build files? Is there any resource you can share?

**Comment by juliancwirko** [comment]
Hi, the build contains standard static files, you should be able to host them with any server. For now there isn't any configured server for public folder, but you can use something like for example [http-server](https://www.npmjs.com/package/http-server) in public folder.

**Comment by infacq** [comment]
I already use that one but upon browser refresh the page requested show 404. Do I need to configure what people call it isomorphism

**Comment by juliancwirko** [comment]
In normal workflow you don't need to run your server to host files from public folder because you have dev server. If you want to serve files locally from that folder you should redirect all calls to the index.html file so for example in apache/php server you can do something like:

```
RewriteEngine On
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

RewriteRule ^ /index.html [L]
```

in `.htaccess` file. 

I don't know how to do this in `http-server`, but I as mentioned you can use dev server and http-server just to check if everything works after build.

You can read more about this 404 refresh problem on StackOverflow.

**Comment by infacq** [comment]
but this won't render on the server right? correct me if I'm wrong

**Comment by juliancwirko** [comment]
Yes, this is only front end boilerplate, but if you want to serve static react files you need to configure your server to be able to redirect url calls to index.html or you can search for some other soultions on the internet. I use it on apache for now so I use redirection. This prevents 404 errors when you hard refresh page on some sup path

**Comment by infacq** [comment]
ok thanks
