### ISSUE TITLE
sGrid link issue

### ISSUE THREAD

**Issue by anaibol** [juliancwirko/react-boilerplate#2]
Hi, it seems that the link on the readme is linking to https://stylusgrid.com/ that doesnt work 'au lieu de' a non secure link http://stylusgrid.com/

Great boilerplate! Thanks for sharing :)

pd: why are you using stylus + postcss?

**Comment by juliancwirko** [comment]
ah, you're right, sorry for that. It is now fixed. Thanks!

This is a good question ;) I use Stylus and PostCSS because I really like stylus and I can't just leave it ;) I probably just abandon Stylus someday. But for now the sGrid is written in stylus and I also like to use it much. And if you are asking why there is a PostCSS at all (so different direction ;)) There is a PostCSS plugin called Autoprefixer (which you probably know) which is needed when working with sGrid. I like to use Autoprefixer that way and not with stylus autoprefixer plugin. If I want I can use other PostCSS plugins too. PostCSS and preprocessors can work side by side.

**Comment by anaibol** [comment]
Ok, thanks for the explanation :)
